#!/usr/bin/with-contenv bash

SCRUTINY_API_ENDPOINT=${SCRUTINY_API_ENDPOINT:-http://localhost:8080}

mkdir -p \
    /config/crontabs \
    /config/log \
    /scrutiny/config

[[ ! -e "/config/scrutiny.yaml" ]] && \
    cp /defaults/scrutiny.yaml /config/scrutiny.yaml

ln -sf /config/scrutiny.yaml /scrutiny/config/scrutiny.yaml

[[ ! -e "/config/collector.yaml" ]] && \
    cp /defaults/collector.yaml /config/collector.yaml

ln -sf /config/collector.yaml /scrutiny/config/collector.yaml

# copy crontab if needed
[[ ! -f /config/crontabs/root ]] && \
	cp /etc/crontabs/root /config/crontabs/

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/
sed -i 's|{SCRUTINY_API_ENDPOINT}|'${SCRUTINY_API_ENDPOINT}'|g' /etc/crontabs/root

# remove services unless they're enabled
if [[ -z "$SCRUTINY_WEB" ]]; then
    rm -rf /etc/services.d/web
fi

if [[ -z "$SCRUTINY_COLLECTOR" ]]; then
    rm -rf /etc/services.d/cron
fi

# permissions
chown -R abc:abc \
	/config \
    /app/scrutiny-web
